// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getLogPath: () => __TAURI_INVOKE<string>("get_log_path"),
	frontendLog: (message: string) => __TAURI_INVOKE<void>("frontend_log", { message }),
	getSettings: () => __TAURI_INVOKE<RouxSettings>("get_settings"),
	updateSettings: (settings: RouxSettings) => typedError<null, string>(__TAURI_INVOKE("update_settings", { settings })),
	checkForUpdate: (channel: UpdateChannel) => typedError<{
	version: string,
	notes: string,
} | null, UpdaterError>(__TAURI_INVOKE("check_for_update", { channel })),
	installUpdate: (channel: UpdateChannel) => typedError<null, UpdaterError>(__TAURI_INVOKE("install_update", { channel })),
	cmdCreateWorktree: (repoPath: string, branch: string, startPoint: string | null, fetchFirst: boolean | null) => typedError<string, string>(__TAURI_INVOKE("cmd_create_worktree", { repoPath, branch, startPoint, fetchFirst })),
	cmdRemoveWorktree: (repoPath: string, worktreePath: string, alsoBranch: boolean | null) => typedError<null, string>(__TAURI_INVOKE("cmd_remove_worktree", { repoPath, worktreePath, alsoBranch })),
	cmdListWorktrees: (repoPath: string) => typedError<Worktree[], string>(__TAURI_INVOKE("cmd_list_worktrees", { repoPath })),
	/**
	 *  Resolve a worktree-base-path template (`{project_dir}`, `{git_root}`,
	 *  `{project_name}`, `{home}`, leading `~/`) against a sample repo path so
	 *  Settings can show a live preview.
	 */
	cmdPreviewWorktreeBase: (template: string, repoPath: string) => __TAURI_INVOKE<string>("cmd_preview_worktree_base", { template, repoPath }),
	cmdDetectWorktrunk: (repoPath: string | null) => __TAURI_INVOKE<WorktrunkDetection>("cmd_detect_worktrunk", { repoPath }),
	cmdWorktrunkDiagnostics: (repoPath: string) => typedError<WorktrunkDiagnostics, string>(__TAURI_INVOKE("cmd_worktrunk_diagnostics", { repoPath })),
	/**
	 *  Read a single worktrunk log file, capped at 256 KiB. Returns `None`
	 *  when the file doesn't exist (was rotated / pruned between listing
	 *  and read).
	 * 
	 *  Defense-in-depth: even though the UI only supplies paths it received
	 *  from `cmd_worktrunk_diagnostics`, we refuse any path whose canonical
	 *  form does not live under `<repo_path>/.git/wt/logs/`. That way a
	 *  compromised frontend / XSS can't turn this into an arbitrary-file
	 *  read primitive.
	 */
	cmdWorktrunkReadLog: (repoPath: string, path: string) => typedError<string | null, string>(__TAURI_INVOKE("cmd_worktrunk_read_log", { repoPath, path })),
	/**
	 *  Open a terminal at `path`. Used by the Worktrunk panel's
	 *  right-click context menu.
	 * 
	 *  macOS: `open -a Terminal <path>` — always Apple Terminal. (The
	 *  user's "default terminal" preference on macOS is not exposed via a
	 *  stable API, so we pick Terminal.app deliberately.)
	 *  Linux: best-effort `xdg-terminal-exec` if available, else
	 *  `x-terminal-emulator` (Debian/Ubuntu wrapper); returns an error
	 *  if neither resolves.
	 *  Windows: `wt.exe -d <path>` (Windows Terminal) — falls back to
	 *  `cmd /c start cmd /k "cd /d <path>"` when Windows Terminal is
	 *  absent or fails.
	 */
	cmdOpenTerminalAt: (path: string) => typedError<null, string>(__TAURI_INVOKE("cmd_open_terminal_at", { path })),
	cmdOpenPathInFinder: (path: string) => typedError<null, string>(__TAURI_INVOKE("cmd_open_path_in_finder", { path })),
	cmdListAutomationHooks: (repoPath: string | null) => typedError<HookListItem[], string>(__TAURI_INVOKE("cmd_list_automation_hooks", { repoPath })),
	cmdPreviewAutomationHooks: (request: HookRunRequest) => typedError<HookPreviewItem[], string>(__TAURI_INVOKE("cmd_preview_automation_hooks", { request })),
	cmdRunAutomationHook: (request: HookRunRequest) => typedError<HookRunSummary, string>(__TAURI_INVOKE("cmd_run_automation_hook", { request })),
	cmdApproveAutomationHook: (approvalId: string) => typedError<null, string>(__TAURI_INVOKE("cmd_approve_automation_hook", { approvalId })),
	cmdClearAutomationHookApprovals: () => typedError<null, string>(__TAURI_INVOKE("cmd_clear_automation_hook_approvals")),
	cmdListAutomationHookLogs: () => __TAURI_INVOKE<HookLogEntry[]>("cmd_list_automation_hook_logs"),
	cmdReadAutomationHookLog: (path: string) => typedError<string, string>(__TAURI_INVOKE("cmd_read_automation_hook_log", { path })),
	writeToSession: (id: string, data: string) => typedError<null, string>(__TAURI_INVOKE("write_to_session", { id, data })),
	resizeSession: (id: string, cols: number, rows: number) => typedError<null, string>(__TAURI_INVOKE("resize_session", { id, cols, rows })),
	spawnShell: (id: string, workingDir: string, sessionId: string | null, paneId: string | null, nonoProfile: string | null, nonoAllowDirs: string[] | null, profile: string | null, initialSize: [number, number] | null) => typedError<null, string>(__TAURI_INVOKE("spawn_shell", { id, workingDir, sessionId, paneId, nonoProfile, nonoAllowDirs, profile, initialSize })),
	spawnTask: (id: string, command: string, workingDir: string, sessionId: string | null, paneId: string | null, profile: string | null, initialSize: [number, number] | null) => typedError<null, string>(__TAURI_INVOKE("spawn_task", { id, command, workingDir, sessionId, paneId, profile, initialSize })),
	/**
	 *  Archive a session (soft-delete). The frontend command name is retained
	 *  for backward-compat, but the record is kept on disk and shown in the
	 *  sessions-history pane until the user permanently deletes it.
	 */
	killSession: (id: string) => typedError<null, string>(__TAURI_INVOKE("kill_session", { id })),
	// Bring an archived session back to the active list.
	restoreSession: (id: string) => typedError<null, string>(__TAURI_INVOKE("restore_session", { id })),
	/**
	 *  Permanently delete a session record. Irreversible. Does not touch the
	 *  worktree — worktree handling is explicit via the History pane's
	 *  Clean worktree action.
	 */
	deleteSessionPermanently: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_session_permanently", { id })),
	/**
	 *  Check whether an archived session's worktree path still exists on disk.
	 *  The frontend uses this to disable the Restore button when the worktree
	 *  has been removed since archival.
	 */
	sessionWorktreeExists: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("session_worktree_exists", { id })),
	/**
	 *  Kill only the PTY for `id`, leaving session state, pane-state files, and
	 *  the session record untouched. Used by `disposePane` on the frontend so
	 *  closing a pane never accidentally destroys its session — even when the
	 *  pane's `ptyId === sessionId` (the session-owned PTY spawned by
	 *  `create_session` / `create_session_shell`).
	 * 
	 *  Prior to this command, `disposePane` called `kill_session`, which tore
	 *  down `session_handle` and `pane_state` as a side effect. That was fine
	 *  for non-primary shells whose ptyId was a random UUID (not in
	 *  `session_handle`) but catastrophic for primary panes, where
	 *  `ptyId == sessionId` matched a real session record and deleted it.
	 */
	killPty: (id: string) => typedError<null, string>(__TAURI_INVOKE("kill_pty", { id })),
	setSessionNameOverride: (sessionId: string, nameOverride: string | null) => typedError<null, string>(__TAURI_INVOKE("set_session_name_override", { sessionId, nameOverride })),
	getPtyGeneration: (id: string) => __TAURI_INVOKE<number | null>("get_pty_generation", { id }),
	/**
	 *  Live cwd of a PTY-backed process, resolved from the OS (no shell hooks).
	 *  Used at pane-state save time so that reconnecting a session restores the
	 *  directory the shell is actually in (after `cd`s), not just the directory
	 *  it was spawned in.
	 */
	getPtyCwd: (id: string) => __TAURI_INVOKE<string | null>("get_pty_cwd", { id }),
	/**
	 *  Spawns a plain shell in the session's
	 *  primary PTY instead of the claude binary. The frontend attaches the
	 *  selected spawn profile and types setup / startup commands after the
	 *  shell is ready. Used for every non-claude profile in the new-session
	 *  picker (Codex, Plain shell, user profiles, inline Custom…).
	 */
	createSessionShell: (repoPath: string, name: string, worktreePath: string | null, branch: string | null, opts: {
	nonoProfile?: string | null,
	nonoAllowDirs?: string[] | null,
	/**
	 *  Spawn-profile id (`claude`, `codex`, user-profile id, …). Passed to
	 *  the PTY env so agents wake up under the right profile.
	 */
	profile?: string | null,
	initialSize?: [number, number] | null,
	/**
	 *  Git starting point for a new worktree's branch (e.g. "main",
	 *  "origin/main"). Ignored unless `branch` is set and new.
	 */
	base?: string | null,
	/**
	 *  Run `git fetch origin` before resolving `base`. Used for
	 *  `origin/*`-style bases that may be stale locally.
	 */
	fetchFirst?: boolean | null,
} | null) => typedError<Session, string>(__TAURI_INVOKE("create_session_shell", { repoPath, name, worktreePath, branch, opts })),
	/**
	 *  Respawns a plain shell in the session's primary PTY. The frontend
	 *  replays the pane's spawn profile commands into the fresh shell after
	 *  this call returns, so agents come back up the same way they were
	 *  originally launched via `create_session_shell`.
	 */
	reconnectSessionShell: (id: string, nonoProfile: string | null, nonoAllowDirs: string[] | null, profile: string | null, initialSize: [number, number] | null) => typedError<Session, string>(__TAURI_INVOKE("reconnect_session_shell", { id, nonoProfile, nonoAllowDirs, profile, initialSize })),
	/**
	 *  Active sessions only — archived rows are excluded. The history view
	 *  uses `list_archived_sessions` for those.
	 */
	listSessions: () => typedError<Session[], string>(__TAURI_INVOKE("list_sessions")),
	/**
	 *  Archived sessions, sorted newest-first by `ended_at` so the history
	 *  pane renders in the order the user closed them.
	 */
	listArchivedSessions: () => typedError<Session[], string>(__TAURI_INVOKE("list_archived_sessions")),
	listClaudeSessions: (cwd: string) => typedError<ClaudeSession[], string>(__TAURI_INVOKE("list_claude_sessions", { cwd })),
	/**
	 *  Return the built-in spawn profile registry, assembled from each provider
	 *  module plus the catch-all "Plain shell". Called once at frontend startup
	 *  to populate the built-in segment of the pane-picker registry. Safe to
	 *  call again any time — the result is derived from current settings and
	 *  has no side effects.
	 */
	getBuiltinProfiles: () => __TAURI_INVOKE<SpawnProfile[]>("get_builtin_profiles"),
	/**
	 *  Return the bundled built-in layouts. Parse errors here would be a
	 *  programming bug (we shipped KDL that doesn't parse); they are logged to
	 *  stderr so they show up in the dev console but the command still returns
	 *  the successfully-parsed layouts.
	 */
	getBuiltinLayouts: () => __TAURI_INVOKE<LayoutSpec[]>("get_builtin_layouts"),
	/**
	 *  Return user-authored layouts from `~/.config/roux/layouts/*.kdl`. Same
	 *  v1 policy as `get_builtin_layouts` — failures are logged, not surfaced.
	 */
	getUserLayouts: () => __TAURI_INVOKE<LayoutSpec[]>("get_user_layouts"),
	/**
	 *  Return the fully-resolved active keymap. On first launch this creates
	 *  `~/.config/roux/keymap.kdl` from the default preset before returning.
	 */
	getKeymap: () => typedError<ParsedKeymap, string>(__TAURI_INVOKE("get_keymap")),
	/**
	 *  Write `contents` to `~/.config/roux/keymap.kdl`. Does not parse — the
	 *  caller (typically the Settings UI) is responsible for validating before
	 *  calling. On success the frontend typically follows up with `get_keymap`
	 *  to reload.
	 */
	setKeymap: (contents: string) => typedError<null, string>(__TAURI_INVOKE("set_keymap", { contents })),
	/**
	 *  Return the raw KDL source of a built-in preset. Used by the Settings UI
	 *  to offer "copy preset to keymap.kdl" and by docs.
	 */
	getBuiltinKeymapPreset: (name: string) => typedError<string, string>(__TAURI_INVOKE("get_builtin_keymap_preset", { name })),
	/**
	 *  Return the absolute path to the user's `keymap.kdl`. Used by the Settings
	 *  UI to offer "Open in editor".
	 */
	getKeymapPath: () => __TAURI_INVOKE<string>("get_keymap_path"),
	readFile: (path: string) => typedError<string, string>(__TAURI_INVOKE("read_file", { path })),
	writeFile: (path: string, contents: string) => typedError<null, string>(__TAURI_INVOKE("write_file", { path, contents })),
	listDocs: (dir: string) => typedError<DocFile[], string>(__TAURI_INVOKE("list_docs", { dir })),
	cmdOpenInEditor: (path: string) => typedError<null, string>(__TAURI_INVOKE("cmd_open_in_editor", { path })),
	cmdListBranches: (repoPath: string) => typedError<string[], string>(__TAURI_INVOKE("cmd_list_branches", { repoPath })),
	checkSetupNeeded: () => __TAURI_INVOKE<boolean>("check_setup_needed"),
	checkSetupStatus: () => __TAURI_INVOKE<SetupStatus>("check_setup_status"),
	runSetup: () => typedError<null, string>(__TAURI_INVOKE("run_setup")),
	checkNonoInstalled: () => __TAURI_INVOKE<boolean>("check_nono_installed"),
	listNonoProfiles: () => __TAURI_INVOKE<string[]>("list_nono_profiles"),
	checkDoctorStatus: () => __TAURI_INVOKE<DoctorStatus>("check_doctor_status"),
	reinstallCli: () => typedError<null, string>(__TAURI_INVOKE("reinstall_cli")),
	reinstallHooks: () => typedError<null, string>(__TAURI_INVOKE("reinstall_hooks")),
	reinstallSkill: () => typedError<null, string>(__TAURI_INVOKE("reinstall_skill")),
	installAllMissing: () => typedError<null, string>(__TAURI_INVOKE("install_all_missing")),
	cmdDetectGh: () => __TAURI_INVOKE<IntegrationDetection>("cmd_detect_gh"),
	cmdDetectGit: () => __TAURI_INVOKE<IntegrationDetection>("cmd_detect_git"),
	checkGhInstalled: () => __TAURI_INVOKE<boolean>("check_gh_installed"),
	lookupPr: (repoPath: string | null, url: string) => typedError<PrInfo, string>(__TAURI_INVOKE("lookup_pr", { repoPath, url })),
	fetchPrBranch: (repoPath: string, number: number, headRef: string, isCrossRepository: boolean) => typedError<string, string>(__TAURI_INVOKE("fetch_pr_branch", { repoPath, number, headRef, isCrossRepository })),
	cloneRepo: (owner: string, repo: string, targetDir: string) => typedError<string, string>(__TAURI_INVOKE("clone_repo", { owner, repo, targetDir })),
	lookupPrForBranch: (repoPath: string, branch: string) => typedError<PrInfo | null, string>(__TAURI_INVOKE("lookup_pr_for_branch", { repoPath, branch })),
	cmdDiscoverTasks: (dir: string) => __TAURI_INVOKE<TaskGroup[]>("cmd_discover_tasks", { dir }),
	cmdLoadTaskOverrides: () => __TAURI_INVOKE<{ [key in string]: { [key in string]: string } }>("cmd_load_task_overrides"),
	cmdSaveTaskOverrides: (overrides: { [key in string]: { [key in string]: string } }) => typedError<null, string>(__TAURI_INVOKE("cmd_save_task_overrides", { overrides })),
	listProjects: () => typedError<Project[], string>(__TAURI_INVOKE("list_projects")),
	createProject: (name: string) => typedError<Project, string>(__TAURI_INVOKE("create_project", { name })),
	removeProject: (id: string) => typedError<null, string>(__TAURI_INVOKE("remove_project", { id })),
	renameProject: (id: string, name: string) => typedError<null, string>(__TAURI_INVOKE("rename_project", { id, name })),
	setSessionProject: (sessionId: string, projectId: string | null) => typedError<null, string>(__TAURI_INVOKE("set_session_project", { sessionId, projectId })),
	notesRead: (target: NotesTarget) => typedError<NotesRead, string>(__TAURI_INVOKE("notes_read", { target })),
	notesWrite: (target: NotesTarget, content: string, tags: string[]) => typedError<null, string>(__TAURI_INVOKE("notes_write", { target, content, tags })),
	notesAppend: (target: NotesTarget, content: string, timestamped: boolean, tags: string[]) => typedError<null, string>(__TAURI_INVOKE("notes_append", { target, content, timestamped, tags })),
	notesPath: (target: NotesTarget, dir: boolean) => typedError<string, string>(__TAURI_INVOKE("notes_path", { target, dir })),
	notesSearch: (query: NotesSearchQuery) => typedError<string[], string>(__TAURI_INVOKE("notes_search", { query })),
	notesVaultRoot: () => typedError<string, string>(__TAURI_INVOKE("notes_vault_root")),
	cmdCreateWatch: (config: CreateWatchConfig) => typedError<Watch, string>(__TAURI_INVOKE("cmd_create_watch", { config })),
	cmdRemoveWatch: (id: string) => typedError<null, string>(__TAURI_INVOKE("cmd_remove_watch", { id })),
	cmdListWatches: () => typedError<Watch[], string>(__TAURI_INVOKE("cmd_list_watches")),
	cmdPauseWatch: (id: string) => typedError<null, string>(__TAURI_INVOKE("cmd_pause_watch", { id })),
	cmdResumeWatch: (id: string) => typedError<null, string>(__TAURI_INVOKE("cmd_resume_watch", { id })),
	notificationsList: () => typedError<Notification[], string>(__TAURI_INVOKE("notifications_list")),
	notificationsListForSession: (sessionId: string | null) => typedError<Notification[], string>(__TAURI_INVOKE("notifications_list_for_session", { sessionId })),
	notificationsUnreadCount: (sessionId: string | null, global: boolean | null) => typedError<number, string>(__TAURI_INVOKE("notifications_unread_count", { sessionId, global })),
	notificationsMarkRead: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("notifications_mark_read", { id })),
	notificationsMarkAllRead: (sessionId: string | null, global: boolean | null) => typedError<number, string>(__TAURI_INVOKE("notifications_mark_all_read", { sessionId, global })),
	notificationsRemove: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("notifications_remove", { id })),
	notificationsClear: (sessionId: string | null, global: boolean | null) => typedError<number, string>(__TAURI_INVOKE("notifications_clear", { sessionId, global })),
	/**
	 *  Push a notification from the frontend. Primarily intended for testing,
	 *  demos, and the eventual `roux notify` CLI bridge; production notifications
	 *  originate in Rust (watches, hooks, tasks, OSC parser).
	 */
	notificationsPush: (request: NotificationRequest) => typedError<Notification, string>(__TAURI_INVOKE("notifications_push", { request })),
	/**
	 *  Remove all notifications whose source matches the given source variant.
	 *  Only the variant is compared — inner fields (e.g. `watch_id`, `pane_id`)
	 *  are ignored — because the `DismissSource` action is "dismiss all of this
	 *  kind", not "dismiss all from exactly this id".
	 */
	notificationsDismissSource: (source: NotificationSource) => typedError<number, string>(__TAURI_INVOKE("notifications_dismiss_source", { source })),
	checkIsGitRepo: (path: string) => __TAURI_INVOKE<boolean>("check_is_git_repo", { path }),
	listGitReposInRoots: (roots: string[], excludeWorktrees: boolean) => __TAURI_INVOKE<string[]>("list_git_repos_in_roots", { roots, excludeWorktrees }),
	gitInit: (path: string) => typedError<null, string>(__TAURI_INVOKE("git_init", { path })),
	refreshSessionGitStatus: (id: string) => typedError<boolean, string>(__TAURI_INVOKE("refresh_session_git_status", { id })),
	quitApp: () => typedError<null, string>(__TAURI_INVOKE("quit_app")),
	listSessionPtys: (sessionId: string) => typedError<PtyInfo[], string>(__TAURI_INVOKE("list_session_ptys", { sessionId })),
	detachPty: (ptyId: string) => typedError<null, string>(__TAURI_INVOKE("detach_pty", { ptyId })),
	attachPtyToPane: (ptyId: string, paneId: string, cols: number, rows: number) => typedError<AttachResult, string>(__TAURI_INVOKE("attach_pty_to_pane", { ptyId, paneId, cols, rows })),
	markPtyRead: (ptyId: string) => typedError<null, string>(__TAURI_INVOKE("mark_pty_read", { ptyId })),
	setPtyName: (ptyId: string, name: string | null) => typedError<null, string>(__TAURI_INVOKE("set_pty_name", { ptyId, name })),
	/**
	 *  List user-supplied terminal themes. The directory is created on first
	 *  call so it's discoverable by the user. Files that fail to parse are
	 *  dropped silently from the response (logged to stderr) — a single bad
	 *  file should not poison the whole picker.
	 */
	listUserTerminalThemes: () => __TAURI_INVOKE<UserTerminalTheme[]>("list_user_terminal_themes"),
	/**
	 *  Absolute path to `~/.config/roux/themes/`. Created if missing so the
	 *  "Reveal" button always lands on a real folder.
	 */
	userThemesDir: () => __TAURI_INVOKE<string>("user_themes_dir"),
};

/* Types */
export type ActionKind = { type: "focusSession"; sessionId: string } | { type: "focusPane"; paneId: string } | { type: "openUrl"; url: string } | { type: "openPath"; path: string } | { type: "runCommand"; commandId: string } | { type: "retryWatch"; watchId: string } | { type: "dismiss" } | { type: "dismissSource" } | { type: "markRead" };

export type AttachResult = {
	replay_bytes: number[],
};

export type Bind = {
	key: KeyRef,
	action: KeymapAction,
};

export type ClaudeSession = {
	sessionId: string,
	summary: string,
	modifiedAt: number,
};

/**
 *  Options bag for `create_session_shell`. Bundled because Specta caps command
 *  signatures at 10 params, and the Claude/Codex/worktree spawn paths all
 *  share the same set of optional configuration.
 */
export type CreateShellOpts = {
	nonoProfile?: string | null,
	nonoAllowDirs?: string[] | null,
	/**
	 *  Spawn-profile id (`claude`, `codex`, user-profile id, …). Passed to
	 *  the PTY env so agents wake up under the right profile.
	 */
	profile?: string | null,
	initialSize?: [number, number] | null,
	/**
	 *  Git starting point for a new worktree's branch (e.g. "main",
	 *  "origin/main"). Ignored unless `branch` is set and new.
	 */
	base?: string | null,
	/**
	 *  Run `git fetch origin` before resolving `base`. Used for
	 *  `origin/*`-style bases that may be stale locally.
	 */
	fetchFirst?: boolean | null,
};

export type CreateWatchConfig = {
	name: string,
	kind: WatchKind,
	mode: WatchMode,
	scope: WatchScope,
	notify?: NotifyConfig | null,
};

export type CursorStyle = "block" | "underline" | "bar";

/**
 * xterm.js renderer selection. `Auto` (default) tries WebGL and silently
 * falls back to the built-in DOM renderer if construction fails or the
 * WebGL context is lost. `On` is identical to `Auto` today — kept as a
 * distinct option because users have a clear mental model from VSCode's
 * `terminal.integrated.gpuAcceleration`. `Off` skips WebGL entirely.
 */
export type GpuAcceleration = "auto" | "on" | "off";

export type DocFile = {
	path: string,
	name: string,
	relativePath: string,
	modified: number,
};

export type DoctorItem = {
	// Stable id used by the frontend to dispatch reinstall actions.
	id: string,
	// Human-readable label.
	label: string,
	// "installed" | "missing" | "unavailable"
	status: string,
	// Optional detail string (install path, version, reason).
	detail: string | null,
	// Whether this item has a reinstall action.
	installable: boolean,
};

export type DoctorStatus = {
	items: DoctorItem[],
};

export type GithubJob = {
	name: string,
	status: string,
	conclusion: string | null,
	failedStep: string | null,
};

export type GroupBy = "repo" | "project";

export type HookListItem = {
	event: string,
	source: HookSourceKind,
	configPath: string,
	name: string,
	command: string,
	approvalId: string | null,
	approved: boolean,
};

export type HookLogEntry = {
	file: string,
	path: string,
	event: string | null,
	name: string | null,
	source: HookSourceKind | null,
	exitCode: number | null,
	startedAt: number | null,
	finishedAt: number | null,
};

export type HookPreviewItem = {
	event: string,
	source: HookSourceKind,
	configPath: string,
	name: string,
	command: string,
	renderedCommand: string,
	approvalId: string | null,
	approved: boolean,
	matched: boolean,
};

export type HookRunRequest = {
	event: string,
	repoPath: string | null,
	worktreePath: string | null,
	branch: string | null,
	sessionId: string | null,
	projectId: string | null,
	taskId: string | null,
	scope: string | null,
	provider: string | null,
	args: string[] | null,
};

export type HookRunSummary = {
	event: string,
	ran: number,
};

export type HookSourceKind = "user" | "project";

// HUD visibility for a tree.
export type HudMode = { kind: "always" } | { kind: "delayed"; ms: number } | { kind: "never" };

export type IntegrationDetection = {
	binaryPath: string | null,
	version: string | null,
};

export type KeepOpen = "always" | "on-error" | "never";

// How a bound key is matched against a `KeyboardEvent`.
export type KeyRef = 
/**
 *  Match `event.code` — survives keyboard-layout quirks (macOS Option
 *  producing `∆` for `j`, etc.). Used for any binding with a modifier
 *  prefix: `Alt+KeyH`, `Cmd+Digit1`, `Ctrl+KeyB`.
 */
{ kind: "physical"; mods: Modifier[]; code: string } | 
/**
 *  Match `event.key` — the logical character after Shift/dead-keys.
 *  Used for bare bindings inside trees: `"h"`, `"%"`, `"Escape"`.
 */
{ kind: "character"; mods: Modifier[]; key: string };

// What a bind fires.
export type KeymapAction = 
// Execute a registered command by id.
{ kind: "command"; id: string } | 
// Promote to a named tree (drill-down within a chord sequence).
{ kind: "enterTree"; tree: string };

export type KeymapTree = {
	name: string,
	sticky?: boolean,
	passthrough?: boolean,
	hud?: HudMode | null,
	binds: Bind[],
};

/**
 *  A non-fatal issue discovered while parsing. Warnings surface through the
 *  notification system; the keymap still loads.
 */
export type KeymapWarning = {
	message: string,
	line: number,
	column: number,
};

/**
 *  A node in a layout's pane tree. Leaves spawn a single shell seeded from a
 *  profile; splits hold ordered children and a direction. The `size` field is
 *  a raw proportional weight in `[0, 100]`; normalization to pane-tree
 *  fractions happens later in the frontend walker, not here.
 * 
 *  `Eq` is deliberately omitted: `size` is an `Option<f32>` and `f32` does
 *  not implement `Eq`. Tests use `PartialEq` with exact float values, which
 *  is fine because sizes come directly from literal tokens in the KDL source.
 */
export type LayoutPaneNode = { kind: "leaf"; profile_ref: LayoutProfileRef; name?: string | null; size?: number | null; cwd?: string | null; 
// Optional nono sandbox profile name (e.g. "default", "permissive").
nono_profile?: string | null; 
// Optional allow_dir entries from a `nono_flags` child block.
nono_allow_dirs?: string[] | null } | { kind: "split"; direction: LayoutSplitDirection; size?: number | null; children: LayoutPaneNode[] };

/**
 *  How a leaf pane references a spawn profile. Registered ids are looked up
 *  at session-creation time against the merged profile registry; inline
 *  profiles are authored directly in the layout file and carry their own
 *  source = [`ProfileSource::Inline`].
 */
export type LayoutProfileRef = { kind: "registered"; id: string } | { kind: "inline"; profile: SpawnProfile };

/**
 *  Where a layout came from. Built-in layouts are bundled with the app;
 *  user layouts live under `<config>/roux/layouts/` (Phase 2).
 */
export type LayoutSource = "builtin" | "user";

/**
 *  A parsed layout. `id` is derived by the loader from the filename stem
 *  (Phase 2) and passed in to [`parse_layout_kdl`] — it is intentionally not
 *  read from the KDL source itself so renaming a file renames the layout.
 * 
 *  `Eq` is omitted because the embedded [`LayoutPaneNode`] carries
 *  `Option<f32>` sizes; see the note on [`LayoutPaneNode`].
 */
export type LayoutSpec = {
	id: string,
	name: string,
	description?: string | null,
	source: LayoutSource,
	root: LayoutPaneNode,
};

/**
 *  Direction of a split node in a layout. Matches `SplitDirection`
 *  in `src/lib/panes/layout.ts` (`h`/`v`) but spelled out for KDL
 *  authors who will reach for the Zellij spellings.
 */
export type LayoutSplitDirection = "horizontal" | "vertical";

export type LibrarySource = {
	id: string,
	kind?: LibrarySourceKind,
	name: string,
	enabled?: boolean,
	order?: number,
	path?: string | null,
	url?: string | null,
	branch?: string | null,
	/**
	 *  Per-source override for skill sync mode. `null`/absent means
	 *  "inherit the global default" (`RouxSettings::library_skill_sync_default`).
	 */
	skillSync?: SkillSyncMode | null,
};

export type LibrarySourceKind = "localRepo" | "gitRepo";

/**
 *  A modifier key. `Cmd` is platform-dispatched: on macOS it matches Meta,
 *  elsewhere it matches Ctrl. The resolver decides which physical flag to
 *  compare against at match time; the stored form is platform-neutral.
 */
export type Modifier = "cmd" | "ctrl" | "alt" | "shift";

export type NotesRead = {
	path: string,
	content: string,
};

export type NotesSearchQuery = {
	tags: string[],
	/**
	 *  Optional scope name (`"global" | "project" | "repo" | "session"`)
	 *  to restrict the walk. `None` walks the whole vault.
	 */
	scope: string | null,
	exact: boolean,
};

/**
 *  Scope + addressing info for a single note file. Sent verbatim from the
 *  frontend or the CLI; the backend resolves the pieces it needs.
 */
export type NotesTarget = {
	// One of `"global" | "project" | "repo" | "session"`.
	scope: string,
	/**
	 *  Session id used to resolve repo/project context. Falls through to
	 *  the focused session on the frontend side when unset.
	 */
	sessionId: string | null,
	/**
	 *  Optional topic filename (without `.md`). `None` targets the scope's
	 *  `notes.md` anchor.
	 */
	topic: string | null,
	/**
	 *  Override the repo/project slug directly (CLI `--repo` / `--project`).
	 *  Ignored for the session scope.
	 */
	overrideSlug: string | null,
};

export type Notification = {
	id: string,
	createdAt: number,
	level: NotificationLevel,
	source: NotificationSource,
	title: string,
	subtitle: string | null,
	body: string | null,
	sessionId: string | null,
	read: boolean,
	actions: NotificationAction[],
	/**
	 *  When set, a subsequent push with the same `dedup_key` updates this
	 *  notification in place instead of creating a new one. Cleared when the
	 *  user reads or dismisses the notification (tracked via `read`).
	 */
	dedupKey?: string | null,
};

export type NotificationAction = {
	id: string,
	label: string,
	kind: ActionKind,
	primary: boolean,
};

export type NotificationLevel = "info" | "success" | "attention" | "warning" | "error";

// Write-side struct used by ingress paths. The store fills in id, created_at, and read=false.
export type NotificationRequest = {
	level: NotificationLevel,
	source: NotificationSource,
	title: string,
	subtitle: string | null,
	body: string | null,
	sessionId: string | null,
	actions: NotificationAction[],
	/**
	 *  Optional dedup key. When set, `NotificationManager::push` will update
	 *  an existing unread notification carrying the same key instead of
	 *  creating a new one. Useful for flood-prone sources like permission
	 *  prompts that fire repeatedly for the same pane.
	 */
	dedupKey?: string | null,
};

export type NotificationSource = { type: "hook"; provider: string } | { type: "watch"; watchId: string } | { type: "task"; paneId: string } | { type: "cli" } | { type: "osc"; code: number; senderId: string | null } | { type: "internal" };

export type NotifyConfig = {
	desktopNotification: boolean,
	onFailure: boolean,
	onSuccess: boolean,
};

/**
 *  What happens to a PTY when its pane is closed.
 * 
 *  - `Kill` — the PTY process is killed immediately.
 *  - `Detach` — the PTY keeps running in the background; it can be
 *    re-attached to another pane later.
 */
export type OnPaneCloseMode = "detach" | "kill";

/**
 *  Fully parsed keymap. `preset_ref` is the raw `preset "<name>"`
 *  reference, if the document declared one; the loader resolves it by
 *  parsing the preset KDL separately and calling [`merge_keymaps`].
 */
export type ParsedKeymap = {
	presetRef?: string | null,
	/**
	 *  `None` when the document did not declare `hud <mode>`. Lets a preset
	 *  overlay without an explicit `hud` line inherit the base preset's
	 *  HUD mode instead of being clobbered by a default.
	 */
	hudDefault: HudMode | null,
	directBinds: Bind[],
	/**
	 *  Keys to drop from the base when merging a preset; only meaningful on
	 *  the "user overlay" side of a merge.
	 */
	unbinds: KeyRef[],
	trees: KeymapTree[],
	prefixes: Prefix[],
	warnings: KeymapWarning[],
};

export type PrCheckRun = {
	name: string,
	conclusion: string | null,
	url: string | null,
};

export type PrInfo = {
	number: number,
	title: string,
	headRef: string,
	headOwner: string,
	isCrossRepository: boolean,
	url: string,
	repoSlug: string,
};

export type PrReview = {
	reviewer: string,
	state: string,
	url: string | null,
};

export type Prefix = {
	key: KeyRef,
	tree: string,
};

/**
 *  Origin of a profile in the registry. Built-in profiles are contributed by
 *  provider modules at compile time; user profiles live in
 *  `RouxSettings.spawn_profiles`; project profiles (reserved) will live in
 *  `.roux/profiles.json` behind a workspace-trust prompt; inline profiles are
 *  ad-hoc from the "Custom…" picker and never registered.
 */
export type ProfileSource = "builtin" | "user" | "project" | "inline";

export type Project = {
	id: string,
	name: string,
};

/**
 *  Agent providers that Roux knows how to light up first-class UI for.
 * 
 *  User-defined profiles may omit `provider` entirely (→ plain shell with
 *  agent UI dark) or piggyback on an existing variant (→ misleading if the
 *  agent does not actually speak the same hook protocol). A truly new agent
 *  requires a provider module — see `src-tauri/src/providers/`.
 */
export type Provider = "claude" | "codex";

// Serializable PTY snapshot for frontend consumption.
export type PtyInfo = {
	id: string,
	session_id: string | null,
	role: PtyRole,
	status: PtyStatus,
	name: string | null,
	working_dir: string | null,
	profile: string | null,
	unread_output: boolean,
	bell_pending: boolean,
};

// Role of a PTY within its session.
export type PtyRole = 
// Main Claude/shell for the session.
"sessionPrimary" | 
// Additional shells, e.g. spawned from a split pane.
"secondary";

// Lifecycle status of a PTY.
export type PtyStatus = 
// PTY is running and attached to a pane.
{ type: "RunningAttached"; pane_id: string } | 
// PTY is running but not currently attached to any pane.
{ type: "RunningDetached"; since_ms: number } | 
// PTY process has exited.
{ type: "Exited"; code: number | null; at_ms: number };

export type RouxSettings = {
	tabPosition: TabPosition,
	tabWidth: number,
	fontSize: number,
	fontFamily: string,
	uiFontFamily?: string,
	lineHeight: number,
	scrollback: number,
	cursorStyle: CursorStyle,
	cursorBlink: boolean,
	defaultProjectPath: string | null,
	repoRoots?: string[],
	excludeWorktreesFromRepoRoots?: boolean,
	confirmOnClose: boolean,
	restoreSessionsOnLaunch: boolean,
	worktreeBasePath: string | null,
	/**
	 *  Legacy boolean kept for backward compatibility with settings files
	 *  written before `worktree_cleanup_on_close` existed. The frontend no
	 *  longer reads this directly; `normalized()` migrates it into the new
	 *  enum and keeps the two in sync for older readers.
	 */
	cleanupWorktreesOnClose: boolean,
	worktreeCleanupOnClose?: WorktreeCleanupMode,
	/**
	 *  Default starting point when the user clicks "New Worktree" directly.
	 *  The flyout / command palette still let them override per-invocation.
	 */
	worktreeDefaultBase?: WorktreeDefaultBase,
	theme: string,
	/**
	 *  Terminal color palette. `"match-gui"` (default) follows the GUI
	 *  theme's bundled terminal palette; any other value names a standalone
	 *  palette (one of the GUI-matching IDs or a built-in editor scheme like
	 *  `dracula`, `solarized-dark`, etc.). Unknown IDs normalize back to
	 *  `"match-gui"` so a future schema addition cannot brick old clients.
	 */
	terminalTheme?: string,
	defaultModel: string | null,
	claudeBinaryPath?: string | null,
	/**
	 *  Absolute path to the `gh` (GitHub CLI) binary. When set and non-empty,
	 *  Roux uses it directly instead of resolving `gh` from `PATH`. macOS
	 *  GUI apps inherit a minimal PATH that often excludes `/opt/homebrew/bin`
	 *  and other shell-managed prefixes, so users on fish/zsh with Homebrew
	 *  typically need to set this explicitly.
	 */
	ghBinaryPath?: string | null,
	/**
	 *  Absolute path to the `git` binary. When set and non-empty, Roux uses
	 *  it for git-backed Library sources instead of resolving `git` from the
	 *  login-shell PATH or process PATH.
	 */
	gitBinaryPath?: string | null,
	/**
	 *  Absolute path to the `wt` (worktrunk) binary. When set and non-empty,
	 *  Roux uses it directly instead of resolving `wt` from `PATH`. Same
	 *  motivation as `gh_binary_path` — macOS GUI apps inherit a minimal
	 *  PATH that often excludes `/opt/homebrew/bin`. Leave unset to resolve
	 *  via the login-shell PATH and fall back to "no worktrunk available"
	 *  when nothing is found.
	 */
	worktrunkBinaryPath?: string | null,
	/**
	 *  Absolute path to the shell binary for terminal panes and login-shell
	 *  PATH discovery. When set and non-empty, overrides automatic resolution
	 *  from the OS login shell, then $SHELL.
	 */
	shellBinaryPath?: string | null,
	/**
	 *  Which backend Roux uses to create worktrees. Default `Auto` prefers
	 *  `wt` when available and falls back to git when not.
	 */
	worktreeProvider?: WorktreeProvider,
	additionalFlags: string[],
	taskPanelSplit: number,
	taskPanelCollapsed: boolean,
	sidebarCollapsed?: boolean,
	enableLogging?: boolean,
	groupBy?: GroupBy,
	confirmOnQuit?: boolean,
	/**
	 *  Master kill-switch for the notification service's OS-notification
	 *  fan-out. When false, notifications still land in the in-app pane but
	 *  `tauri-plugin-notification` is never invoked. Defaults to true.
	 */
	notificationsEnabled?: boolean,
	/**
	 *  When a background agent leaves the "attention" (waiting-for-answer)
	 *  state, also clear the pane's `permissionInfo` so the Claude
	 *  Allow/Deny affordance disappears alongside the notification.
	 *  Defaults to true — rollback insurance only.
	 */
	autoClearAttentionState?: boolean,
	/**
	 *  Whether Roux checks for updates silently on launch. Manual checks via
	 *  Settings / command palette remain available regardless.
	 */
	updateCheckOnLaunch?: boolean,
	/**
	 *  Experimental multi-scoped notes — when true (the default), the
	 *  timestamped-append CLI verb prefixes each entry with an inline
	 *  `<a id="entry-...">` HTML anchor so the entry is deep-linkable
	 *  from any mainstream static-site generator. Disable for cleaner
	 *  raw markdown if you only read the vault in Obsidian.
	 */
	notesIncludeWebAnchors?: boolean,
	/**
	 *  Experimental multi-scoped notes — override for the vault root
	 *  directory. `None` means "use the default `~/Documents/Roux`".
	 */
	notesVaultRoot?: string | null,
	/**
	 *  Experimental multi-scoped notes — set to `true` once the legacy
	 *  `<project_id>.txt` files have been migrated into the vault. Guards
	 *  against re-running the migration on every app launch.
	 */
	notesMigratedV1?: boolean,
	/**
	 *  Which update channel this user is subscribed to. `Stable` pulls from the
	 *  standard `latest.json` manifest; `PreRelease` resolves the newest
	 *  GitHub prerelease at check time and pulls its `latest-prerelease.json`.
	 */
	updateChannel?: UpdateChannel,
	/**
	 *  User-defined spawn profiles. Edited as raw JSON in the settings file
	 *  in v1 — the "Save as user profile" UI is a later addition. The settings
	 *  loader force-sets `source: "user"` on each entry regardless of what
	 *  the file says, so users can't forge a `"builtin"` marker.
	 */
	spawnProfiles?: SpawnProfile[],
	/**
	 *  Absolute paths of workspaces the user has marked trusted for the
	 *  future project-profile loader (`.roux/profiles.json`). Reserved in
	 *  phase 3; the loader that consumes this list ships later. Storing the
	 *  field now means the trust prompt and its toggles will not require a
	 *  settings schema bump when they arrive.
	 */
	trustedWorkspaces?: string[],
	/**
	 *  Ordered git repositories that contribute reusable Library items
	 *  under `.roux/library/prompts/` and `.roux/library/skills/`.
	 *  The active repo is layered separately at runtime and wins over these.
	 */
	libraryPinnedRepos?: string[],
	/**
	 *  Ordered Library sources. Local repo sources read `.roux/library` from
	 *  an existing checkout; Git repo sources are managed by Roux and synced
	 *  through native Git operations.
	 */
	librarySources?: LibrarySource[],
	statusBarPosition?: StatusBarPosition,
	/**
	 *  Reveal the pane-number overlay while Option (⌥) is held. The
	 *  `Option+digit` / `Option+HJKL` chord shortcuts are unaffected either way.
	 */
	showPaneHintsOnOption?: boolean,
	/**
	 *  Reveal the session-shortcut overlay while the primary modifier
	 *  (⌘ on macOS, Ctrl elsewhere) is held. Chord shortcuts are unaffected.
	 */
	showSessionHintsOnCommand?: boolean,
	/**
	 *  What happens to a PTY when its pane is closed.
	 *  `Kill` (default): the process is killed immediately.
	 *  `Detach`: the process keeps running and can be re-attached.
	 */
	onPaneClose?: OnPaneCloseMode,
	/**
	 *  Set to `true` once the global Library skills have been rewritten to
	 *  the SKILL.md-compatible format (adds a `name:` field, strips legacy
	 *  `variables:` blocks). Guards against re-running on every launch.
	 */
	librarySkillFormatV2Migrated?: boolean,
	/**
	 *  Default skill-sync mode applied to Library sources that don't
	 *  override it (`LibrarySource::skill_sync`), to the global vault,
	 *  and to the active session repo. Defaults to `Off` so existing
	 *  users see no behavior change after upgrade.
	 */
	librarySkillSyncDefault?: SkillSyncMode,
	/**
	 *  xterm.js renderer hint. `Auto` (default) tries WebGL with DOM fallback.
	 *  Setting changes apply to terminals created afterward; existing panes
	 *  keep their renderer until reopened.
	 */
	gpuAcceleration?: GpuAcceleration,
	/**
	 *  When true, sessions whose worktree branch resolves to an open GitHub
	 *  PR get a session-scoped `GithubPr` watch created automatically. The
	 *  status-bar PR link is shown regardless of this setting; only the
	 *  background watch creation is gated. Defaults to `false` so users
	 *  don't get unexpected new watches on upgrade.
	 */
	autoWatchSessionPr?: boolean,
	/**
	 *  Master switch for the gh-backed session-PR lookup. When true (the
	 *  default), session activation triggers a `gh pr list --head <branch>`
	 *  call to populate the status-bar PR chip and feed the auto-watch
	 *  flow. When false, no gh call is made, the chip falls back to
	 *  worktrunk's `ciUrl` only, and `autoWatchSessionPr` becomes a no-op.
	 */
	autoLookupSessionPr?: boolean,
};

/**
 *  Whether and how a Library source's skills are written into a
 *  Claude-readable `.claude/skills/<name>/SKILL.md` directory.
 */
export type SkillSyncMode = "off" | "copy" | "symlink";

export type RuntimeState = { type: "pending" } | { type: "active" } | { type: "paused" } | { type: "stopped" } | { type: "error"; message: string };

export type Session = {
	id: string,
	name: string,
	repoRoot: string,
	worktreePath: string,
	branch: string,
	isWorktree: boolean,
	status: SessionStatus,
	model: string | null,
	cost: number | null,
	createdAt: number,
	projectId?: string | null,
	isGitRepo?: boolean,
	nameOverride?: string | null,
	/**
	 *  ID of the primary PTY for this session. Set at session creation,
	 *  kept as `None` for sessions restored from disk that haven't reconnected yet.
	 */
	primaryPtyId?: string | null,
	/**
	 *  Soft-delete flag. Archived sessions are retained in `sessions.json`
	 *  for the history view but filtered out of the active `list_sessions`
	 *  query. Restore flips this back to `false`.
	 */
	archived?: boolean,
	/**
	 *  Unix epoch seconds of when this session was archived. `None` for
	 *  active sessions; set when `archived` flips to `true`.
	 */
	endedAt?: number | null,
};

export type SessionStatus = "idle" | "thinking" | "generating" | "error" | "disconnected" | "attention";

export type SetupStatus = {
	cliInstalled: boolean,
	ghAvailable: boolean,
};

/**
 *  A named recipe for launching something inside a shell pane. Orthogonal to
 *  pane type: every launched pane is a shell, and a profile is just optional
 *  metadata attached at creation describing how the shell was seeded.
 * 
 *  Provider-specific UI (Claude Allow/Deny, resume picker) is gated on
 *  observed [`crate::...`]-style runtime agent state, not on this `provider`
 *  field — the field is a UX hint saying "panes launched from this profile
 *  are *expected* to produce hook events from this provider".
 */
export type SpawnProfile = {
	id: string,
	name: string,
	setupCommand?: string | null,
	startupCommand?: string | null,
	startupBehavior?: StartupBehavior | null,
	env?: { [key in string]: string } | null,
	cwdOverride?: string | null,
	icon?: string | null,
	provider?: Provider | null,
	nonoProfile?: string | null,
	nonoAllowDirs?: string[] | null,
	source: ProfileSource,
};

/**
 *  Controls whether the profile's `startup_command` runs immediately or is
 *  only typed into the shell for the user to review before pressing Enter.
 */
export type StartupBehavior = "autoRun" | "typeOnly";

export type StatusBarPosition = "top" | "bottom";

export type TabPosition = "left" | "right";

export type TaskDefinition = {
	id: string,
	name: string,
	description: string,
	runner: string,
	command: string,
	keepOpen: KeepOpen,
};

export type TaskGroup = {
	runner: string,
	configFile: string,
	tasks: TaskDefinition[],
};

/**
 *  16-color ANSI palette plus the special UI slots, mirroring the frontend
 *  `TerminalTheme` shape so the bindings stay 1:1.
 */
export type TerminalAnsiPalette = {
	black: string,
	red: string,
	green: string,
	yellow: string,
	blue: string,
	magenta: string,
	cyan: string,
	white: string,
	brightBlack: string,
	brightRed: string,
	brightGreen: string,
	brightYellow: string,
	brightBlue: string,
	brightMagenta: string,
	brightCyan: string,
	brightWhite: string,
};

export type TerminalThemePalette = {
	background: string,
	foreground: string,
	cursor: string,
	selectionBackground: string,
	ansi: TerminalAnsiPalette,
};

export type UpdateChannel = "stable" | "preRelease";

export type UpdateInfo = {
	version: string,
	notes: string,
};

export type UpdaterError = { kind: "network" } | { kind: "signature-invalid" } | { kind: "not-found" } | { kind: "internal"; message: string };

export type UserTerminalTheme = {
	/**
	 *  `"user:" + filename-stem`. Stable across reloads, so settings can
	 *  persist a reference to a user theme even when the file is briefly
	 *  missing.
	 */
	id: string,
	// Human label derived from the filename stem.
	label: string,
	palette: TerminalThemePalette,
};

export type Watch = {
	id: string,
	name: string,
	kind: WatchKind,
	mode: WatchMode,
	scope: WatchScope,
	runtimeState: RuntimeState,
	lastResult: WatchResult | null,
	lastChecked: number | null,
	notify: NotifyConfig,
	createdAt: number,
};

export type WatchKind = { type: "githubAction"; repo: string; runId: number | null; workflow: string | null; branch: string | null } | { type: "httpHealth"; url: string; expectedStatus: number } | { type: "shellCommand"; command: string; workingDir: string | null; successExitCode: number } | { type: "task"; taskId: string; command: string; workingDir: string } | { type: "githubPr"; repo: string; prNumber: number };

export type WatchMode = { type: "recurring"; intervalSecs: number } | { type: "oneShot" };

export type WatchOutcome = "success" | "failure" | "inProgress";

export type WatchResult = { type: "githubRun"; runId: number; status: string; conclusion: string | null; url: string; jobs: GithubJob[]; outcome: WatchOutcome } | { type: "httpCheck"; statusCode: number; responseTimeMs: number; outcome: WatchOutcome } | { type: "commandRun"; exitCode: number; stdout: string; stderr: string; outcome: WatchOutcome } | { type: "githubPr"; prNumber: number; state: string; title: string; url: string; headSha: string; draft: boolean; reviews: PrReview[]; checks: PrCheckRun[]; outcome: WatchOutcome };

export type WatchScope = { type: "global" } | { type: "session"; sessionId: string } | { type: "project"; projectId: string };

export type Worktree = {
	path: string,
	branch: string,
	isMain: boolean,
	/**
	 *  Optional metadata sourced from `wt list --format=json` when the
	 *  worktrunk CLI is available. `null` means either `wt` is not
	 *  installed or the current command did not attempt enrichment.
	 */
	worktrunk: WorktrunkMetadata | null,
};

/**
 *  Behavior when a session that owns a worktree is closed.
 * 
 *  - `Never` — leave the worktree on disk
 *  - `Prompt` — ask the user via a confirm dialog (current default, matches
 *    the legacy `cleanupWorktreesOnClose: false` behavior)
 *  - `Always` — remove without asking (matches legacy `true`)
 */
export type WorktreeCleanupMode = "never" | "prompt" | "always";

/**
 *  Which starting point the "New Worktree" affordance uses when the user
 *  clicks the primary action directly (as opposed to hovering to pick a
 *  specific base from the flyout). Only affects the default — the three
 *  options remain available via the submenu / command palette either way.
 * 
 *  - `CurrentBranch` — the session's current branch (matches legacy behavior)
 *  - `Main` — the local `main` branch
 *  - `OriginMain` — the remote `origin/main`, with a `git fetch origin` first
 */
export type WorktreeDefaultBase = "currentBranch" | "main" | "originMain";

/**
 *  Which backend Roux uses to create worktrees.
 * 
 *  - `Auto` (default) — use `wt` when it is detected on the system;
 *    otherwise fall back to native `git worktree add`. This is the
 *    recommended setting: users without worktrunk see no change, users
 *    with worktrunk get its hooks/templates/project config for free.
 *  - `Git` — always use native git. Useful as an escape hatch if a
 *    worktrunk hook is misbehaving.
 *  - `Worktrunk` — always prefer `wt`. If `wt` fails for any reason,
 *    Roux still falls back to native git so worktree creation never
 *    breaks entirely — the setting expresses preference, not veto.
 */
export type WorktreeProvider = "auto" | "git" | "worktrunk";

// Summary of where worktrunk's configs live on disk.
export type WorktrunkConfigSummary = {
	userPath: string,
	userExists: boolean,
	projectPath: string,
	projectExists: boolean,
};

/**
 *  Result of probing the user's environment for a usable worktrunk install.
 *  Either field can be populated independently: the binary may be on PATH
 *  without any project config, or a project may carry `.config/wt.toml`
 *  without the user having the CLI installed.
 */
export type WorktrunkDetection = {
	/**
	 *  Resolved binary path, when detection succeeds and the version meets
	 *  `roux_worktrunk::MIN_WT_VERSION`. `null` when no usable wt is found.
	 */
	binaryPath: string | null,
	// Human-readable version string (e.g. "0.44.0") when binary_path is set.
	version: string | null,
	// True when `{repo_path}/.config/wt.toml` exists as a file.
	hasConfig: boolean,
};

// Everything the Worktrunk sidebar panel needs in a single call.
export type WorktrunkDiagnostics = {
	hooks: WorktrunkHookDef[],
	config: WorktrunkConfigSummary,
	logs: WorktrunkLogsSummary,
};

// Hook definition extracted from a worktrunk config file.
export type WorktrunkHookDef = {
	// "user" or "project".
	source: string,
	// Absolute path to the config file this hook lives in.
	configPath: string,
	// e.g. "post-start", "pre-merge".
	name: string,
	/**
	 *  Displayable command value — a plain string for simple hooks, a
	 *  JSON-encoded string for array/object values.
	 */
	command: string,
};

// Hook-output log entry with extra fields identifying which hook fired.
export type WorktrunkHookOutputEntry = {
	file: string,
	path: string,
	size: number,
	modifiedAt: number | null,
	branch: string,
	source: string,
	hookType: string | null,
	name: string,
};

// One log-file entry (command log or diagnostic).
export type WorktrunkLogEntry = {
	file: string,
	path: string,
	size: number,
	modifiedAt: number | null,
};

export type WorktrunkLogsSummary = {
	commandLog: WorktrunkLogEntry[],
	hookOutput: WorktrunkHookOutputEntry[],
	diagnostic: WorktrunkLogEntry[],
};

export type WorktrunkMetadata = {
	dirty: boolean,
	ahead: number,
	behind: number,
	locked: boolean,
	lockReason: string | null,
	prunable: boolean,
	prunableReason: string | null,
	isCurrent: boolean,
	isPrevious: boolean,
	devServerUrl: string | null,
	/**
	 *  Branch's relationship to the default branch as reported by wt.
	 *  Common values: "is_main" (same as main), "integrated" (merged),
	 *  "diverged", "ahead", "behind", "same_commit", "would_conflict".
	 *  Absent for entries wt can't classify.
	 */
	mainState: string | null,
	/**
	 *  CI status summary — "passed" | "failed" | "running" | "conflicts"
	 *  | "no-ci" | "error". `null` when wt has no CI data for the branch.
	 */
	ciStatus: string | null,
	// Link to the PR or workflow run when wt surfaced one.
	ciUrl: string | null,
	/**
	 *  True when the CI status is for an older commit than local HEAD
	 *  (there are unpushed changes).
	 */
	ciStale: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}
