import type { ITheme } from "@xterm/xterm";
import type { ThemePreset } from "$lib/types";

export interface ThemeDefinition {
  id: ThemePreset;
  label: string;
  description: string;
  light?: boolean;
}

export const THEME_DEFINITIONS: ThemeDefinition[] = [
  {
    id: "deep-blue",
    label: "Refined Zinc",
    description: "Neutral industrial grays with sky accents. The default.",
  },
  {
    id: "midnight-copper",
    label: "Midnight Copper",
    description: "Smoky navy workspace with copper highlights.",
  },
  {
    id: "steel-amber",
    label: "Steel Amber",
    description: "Warm chrome with amber highlights.",
  },
  {
    id: "slate-emerald",
    label: "Slate Emerald",
    description: "Dark slate with calmer green accents.",
  },
  {
    id: "graphite-rose",
    label: "Graphite Rose",
    description: "Graphite UI with rose and violet accents.",
  },
  {
    id: "nordic-night",
    label: "Nordic Night",
    description: "Cool blue-grays with teal accents. Inspired by Nord.",
  },
  {
    id: "cyber-audit",
    label: "Cyber Audit",
    description: "High contrast black with lime accents.",
  },
  {
    id: "mocha-soft",
    label: "Mocha Soft",
    description: "Warm dark palette inspired by Catppuccin.",
  },
  {
    id: "paper-ink",
    label: "Paper & Ink",
    description: "Clean light theme with a recessed dark terminal.",
    light: true,
  },
  {
    id: "github-day",
    label: "GitHub Day",
    description: "Light UI with a dark terminal workspace.",
    light: true,
  },
];

export const LIGHT_THEMES: Set<ThemePreset> = new Set(
  THEME_DEFINITIONS.filter((t) => t.light).map((t) => t.id),
);

const DEFAULT_THEME: ThemePreset = "deep-blue";

export function normalizeTheme(theme: string | null | undefined): ThemePreset {
  if (!theme || theme === "dark") {
    return DEFAULT_THEME;
  }

  return THEME_DEFINITIONS.some((definition) => definition.id === theme)
    ? (theme as ThemePreset)
    : DEFAULT_THEME;
}

export function isLightTheme(theme: ThemePreset): boolean {
  return LIGHT_THEMES.has(theme);
}

const XTERM_THEMES: Record<ThemePreset, ITheme> = {
  "deep-blue": {
    background: "#09090b",
    foreground: "#fafafa",
    cursor: "#7dd3fc",
    selectionBackground: "#27272acc",
    black: "#09090b",
    red: "#fb7185",
    green: "#4ade80",
    yellow: "#fbbf24",
    blue: "#38bdf8",
    magenta: "#c084fc",
    cyan: "#67e8f9",
    white: "#fafafa",
    brightBlack: "#52525b",
    brightRed: "#fda4af",
    brightGreen: "#86efac",
    brightYellow: "#fde68a",
    brightBlue: "#7dd3fc",
    brightMagenta: "#d8b4fe",
    brightCyan: "#a5f3fc",
    brightWhite: "#fafafa",
  },
  "midnight-copper": {
    background: "#171d2a",
    foreground: "#d6deeb",
    cursor: "#f29d6f",
    selectionBackground: "#2e3b5688",
    black: "#171d2a",
    red: "#ef8a77",
    green: "#8bcf9f",
    yellow: "#f2b37f",
    blue: "#6f95d8",
    magenta: "#b39ddb",
    cyan: "#7fb8c9",
    white: "#d6deeb",
    brightBlack: "#4a556d",
    brightRed: "#f6a596",
    brightGreen: "#a9dcb7",
    brightYellow: "#f7cfa9",
    brightBlue: "#90afeb",
    brightMagenta: "#c8b6e5",
    brightCyan: "#9fceda",
    brightWhite: "#e9effa",
  },
  "steel-amber": {
    background: "#09090b",
    foreground: "#fafaf9",
    cursor: "#f59e0b",
    selectionBackground: "#27272acc",
    black: "#09090b",
    red: "#fb7185",
    green: "#86efac",
    yellow: "#f59e0b",
    blue: "#94a3b8",
    magenta: "#c084fc",
    cyan: "#cbd5e1",
    white: "#f1f5f9",
    brightBlack: "#52525b",
    brightRed: "#fda4af",
    brightGreen: "#bbf7d0",
    brightYellow: "#fcd34d",
    brightBlue: "#cbd5e1",
    brightMagenta: "#e9d5ff",
    brightCyan: "#e2e8f0",
    brightWhite: "#fafaf9",
  },
  "slate-emerald": {
    background: "#09090b",
    foreground: "#e7f7f2",
    cursor: "#34d399",
    selectionBackground: "#15332ccc",
    black: "#09090b",
    red: "#fb7185",
    green: "#34d399",
    yellow: "#fbbf24",
    blue: "#60a5fa",
    magenta: "#a78bfa",
    cyan: "#5eead4",
    white: "#e7f7f2",
    brightBlack: "#4b635c",
    brightRed: "#fda4af",
    brightGreen: "#6ee7b7",
    brightYellow: "#fde68a",
    brightBlue: "#93c5fd",
    brightMagenta: "#c4b5fd",
    brightCyan: "#99f6e4",
    brightWhite: "#f0fdfa",
  },
  "graphite-rose": {
    background: "#09090b",
    foreground: "#f5f2f8",
    cursor: "#fb7185",
    selectionBackground: "#2b1830cc",
    black: "#09090b",
    red: "#fb7185",
    green: "#4ade80",
    yellow: "#fbbf24",
    blue: "#a78bfa",
    magenta: "#f472b6",
    cyan: "#94a3b8",
    white: "#f5f2f8",
    brightBlack: "#5b5464",
    brightRed: "#fda4af",
    brightGreen: "#86efac",
    brightYellow: "#fde68a",
    brightBlue: "#c4b5fd",
    brightMagenta: "#f9a8d4",
    brightCyan: "#cbd5e1",
    brightWhite: "#faf5ff",
  },
  "nordic-night": {
    background: "#0c0e14",
    foreground: "#d8dee9",
    cursor: "#2dd4bf",
    selectionBackground: "#2e344088",
    black: "#0c0e14",
    red: "#bf616a",
    green: "#a3be8c",
    yellow: "#ebcb8b",
    blue: "#81a1c1",
    magenta: "#b48ead",
    cyan: "#88c0d0",
    white: "#d8dee9",
    brightBlack: "#4c566a",
    brightRed: "#d08770",
    brightGreen: "#a3be8c",
    brightYellow: "#ebcb8b",
    brightBlue: "#5e81ac",
    brightMagenta: "#b48ead",
    brightCyan: "#8fbcbb",
    brightWhite: "#eceff4",
  },
  "cyber-audit": {
    background: "#000000",
    foreground: "#ffffff",
    cursor: "#a3e635",
    selectionBackground: "#27272a88",
    black: "#000000",
    red: "#e11d48",
    green: "#a3e635",
    yellow: "#facc15",
    blue: "#38bdf8",
    magenta: "#d946ef",
    cyan: "#22d3ee",
    white: "#ffffff",
    brightBlack: "#52525b",
    brightRed: "#fb7185",
    brightGreen: "#bef264",
    brightYellow: "#fde68a",
    brightBlue: "#7dd3fc",
    brightMagenta: "#e879f9",
    brightCyan: "#67e8f9",
    brightWhite: "#ffffff",
  },
  "mocha-soft": {
    background: "#1e1e2e",
    foreground: "#cdd6f4",
    cursor: "#89b4fa",
    selectionBackground: "#31324488",
    black: "#45475a",
    red: "#f38ba8",
    green: "#a6e3a1",
    yellow: "#f9e2af",
    blue: "#89b4fa",
    magenta: "#cba6f7",
    cyan: "#94e2d5",
    white: "#bac2de",
    brightBlack: "#585b70",
    brightRed: "#f38ba8",
    brightGreen: "#a6e3a1",
    brightYellow: "#f9e2af",
    brightBlue: "#89b4fa",
    brightMagenta: "#cba6f7",
    brightCyan: "#94e2d5",
    brightWhite: "#a6adc8",
  },
  // Light themes use a dark terminal
  "paper-ink": {
    background: "#1c1c1c",
    foreground: "#e4e4e4",
    cursor: "#2563eb",
    selectionBackground: "#3b3b3b88",
    black: "#1c1c1c",
    red: "#dc2626",
    green: "#16a34a",
    yellow: "#ca8a04",
    blue: "#2563eb",
    magenta: "#9333ea",
    cyan: "#0891b2",
    white: "#e4e4e4",
    brightBlack: "#525252",
    brightRed: "#ef4444",
    brightGreen: "#22c55e",
    brightYellow: "#eab308",
    brightBlue: "#3b82f6",
    brightMagenta: "#a855f7",
    brightCyan: "#06b6d4",
    brightWhite: "#fafafa",
  },
  "github-day": {
    background: "#0d1117",
    foreground: "#e6edf3",
    cursor: "#58a6ff",
    selectionBackground: "#26384888",
    black: "#0d1117",
    red: "#ff7b72",
    green: "#7ee787",
    yellow: "#d29922",
    blue: "#58a6ff",
    magenta: "#bc8cff",
    cyan: "#39d353",
    white: "#e6edf3",
    brightBlack: "#484f58",
    brightRed: "#ffa198",
    brightGreen: "#56d364",
    brightYellow: "#e3b341",
    brightBlue: "#79c0ff",
    brightMagenta: "#d2a8ff",
    brightCyan: "#56d364",
    brightWhite: "#f0f6fc",
  },
};

export function getXtermTheme(theme: string | null | undefined): ITheme {
  return XTERM_THEMES[normalizeTheme(theme)];
}
