// Import generated types from specta bindings
import type { RouxSettings } from "./bindings";

// Re-export generated types
export type { RouxSettings };
export type {
  Session as BaseSession,
  SessionStatus,
  Project,
  CursorStyle,
  TabPosition,
  StatusBarPosition,
  GroupBy,
  WorktreeCleanupMode,
  Worktree,
  ClaudeSession,
  Watch,
  WatchKind,
  WatchMode,
  WatchScope,
  WatchResult,
  WatchOutcome,
  CreateWatchConfig,
  RuntimeState,
  NotifyConfig,
  GithubJob,
  PrReview,
  PrCheckRun,
  TaskDefinition,
  TaskGroup,
  KeepOpen,
  DocFile,
  SetupStatus,
  Notification,
  NotificationAction,
  NotificationLevel,
  NotificationRequest,
  NotificationSource,
  ActionKind,
} from "./bindings";

// Frontend-only types (not defined in Rust)

export type ThemePreset =
  | "deep-blue"
  | "steel-amber"
  | "slate-emerald"
  | "graphite-rose"
  | "nordic-night"
  | "cyber-audit"
  | "mocha-soft"
  | "paper-ink"
  | "github-day";

// Session is exactly the Rust type; permission state now lives in the
// notification service (Phase 3 retired the inline Allow/Deny flow).
export type Session = import("./bindings").Session;

export interface SessionStatusPayload {
  status: string;
  model: string | null;
  cost: number | null;
}

export const DEFAULT_SETTINGS: RouxSettings = {
  tabPosition: "left",
  tabWidth: 260,
  fontSize: 14,
  fontFamily: "JetBrains Mono, IBM Plex Mono, SFMono-Regular, monospace",
  uiFontFamily: "Geist, Inter, SF Pro Display, Segoe UI, sans-serif",
  lineHeight: 1.2,
  scrollback: 5000,
  cursorStyle: "block",
  cursorBlink: true,
  defaultProjectPath: null,
  repoRoots: [],
  excludeWorktreesFromRepoRoots: true,
  confirmOnClose: true,
  restoreSessionsOnLaunch: true,
  worktreeBasePath: null,
  cleanupWorktreesOnClose: false,
  worktreeCleanupOnClose: "prompt",
  theme: "deep-blue",
  defaultModel: null,
  claudeBinaryPath: null,
  ghBinaryPath: null,
  additionalFlags: [],
  taskPanelSplit: 0.4,
  taskPanelCollapsed: false,
  sidebarCollapsed: false,
  enableLogging: false,
  groupBy: "repo",
  confirmOnQuit: true,
  notificationsEnabled: true,
  updateCheckOnLaunch: true,
  spawnProfiles: [],
  trustedWorkspaces: [],
  statusBarPosition: "bottom",
};

// Re-export frontend-only task types
export type { TaskRun } from "./types/tasks";

// Re-export event types (not yet generated by specta)
export type { WatchUpdateEvent } from "./types/watches";
