// Import generated types from specta bindings
import type { ExperimentsConfig, RouxSettings } from "./bindings";

// Typed defaults for every experiment flag. Adding a new optional field to
// `ExperimentsConfig` will fail to compile here until a default is supplied,
// keeping `RequiredExperiments` consumers (e.g. the SettingsPanel fallback,
// `readExperiments()`) honest about what they can read.
export const EXPERIMENT_DEFAULTS: Required<ExperimentsConfig> = {};

// Re-export generated types
export type { RouxSettings };
export type {
  Session as BaseSession,
  SessionStatus,
  Project,
  ProjectUpdate,
  SessionBlueprint,
  CursorStyle,
  TabPosition,
  StatusBarPosition,
  GroupBy,
  WorktreeCleanupMode,
  WorktreeDefaultBase,
  OnPaneCloseMode,
  Worktree,
  WorktrunkMetadata,
  ClaudeSession,
  Watch,
  WatchKind,
  WatchMode,
  WatchScope,
  WatchResult,
  WatchOutcome,
  CreateWatchConfig,
  RuntimeState,
  NotifyConfig,
  GithubJob,
  PrReview,
  PrCheckRun,
  TaskDefinition,
  TaskGroup,
  KeepOpen,
  DocFile,
  SetupStatus,
  Notification,
  NotificationAction,
  NotificationLevel,
  NotificationRequest,
  NotificationSource,
  ActionKind,
  AttachResult,
  PtyInfo,
  PtyRole,
  PtyStatus,
  ExternalTool,
  ExternalToolSurface,
  ExternalToolWebEmbedder,
} from "./bindings";

// Frontend-only types (not defined in Rust)

export type ThemePreset =
  | "deep-blue"
  | "midnight-copper"
  | "steel-amber"
  | "slate-emerald"
  | "graphite-rose"
  | "nordic-night"
  | "cyber-audit"
  | "mocha-soft"
  | "paper-ink"
  | "github-day"
  | "warm-burnout-dark"
  | "warm-burnout-light";

// Session is exactly the Rust type; permission state now lives in the
// notification service (Phase 3 retired the inline Allow/Deny flow).
export type Session = import("./bindings").Session;

export interface SessionStatusPayload {
  status: string;
  model: string | null;
  cost: number | null;
}

export const DEFAULT_SETTINGS: RouxSettings = {
  tabPosition: "left",
  tabWidth: 260,
  fontSize: 14,
  fontFamily: "JetBrains Mono, IBM Plex Mono, SFMono-Regular, monospace",
  uiFontFamily: "Geist, Inter, SF Pro Display, Segoe UI, sans-serif",
  lineHeight: 1.2,
  scrollback: 5000,
  cursorStyle: "block",
  cursorBlink: true,
  defaultProjectPath: null,
  repoRoots: [],
  excludeWorktreesFromRepoRoots: true,
  confirmOnClose: true,
  restoreSessionsOnLaunch: true,
  worktreeBasePath: null,
  cleanupWorktreesOnClose: false,
  worktreeCleanupOnClose: "prompt",
  worktreeDefaultBase: "currentBranch",
  theme: "deep-blue",
  terminalTheme: "match-gui",
  defaultModel: null,
  claudeBinaryPath: null,
  ghBinaryPath: null,
  gitBinaryPath: null,
  additionalFlags: [],
  taskPanelSplit: 0.4,
  taskPanelCollapsed: false,
  sidebarCollapsed: false,
  enableLogging: false,
  groupBy: "repo",
  confirmOnQuit: true,
  notificationsEnabled: true,
  agentCompletionNotificationsEnabled: true,
  updateCheckOnLaunch: true,
  spawnProfiles: [],
  trustedWorkspaces: [],
  libraryPinnedRepos: [],
  librarySources: [],
  statusBarPosition: "bottom",
  onPaneClose: "kill",
  librarySkillSyncDefault: "off",
  gpuAcceleration: "auto",
  autoLookupSessionPr: true,
  autoWatchSessionPr: false,
  mcpEnabled: false,
  mcpLastConfiguredHost: null,
  mcpLastConfiguredAtMs: null,
  externalTools: [
    {
      id: "lazygit",
      name: "Lazygit",
      enabled: true,
      surface: "terminal",
      commandTemplate: "lazygit -p {{ session.worktree_path | shell_quote }}",
      cwdTemplate: "{{ session.worktree_path }}",
      requiresSession: true,
      urlTemplate: null,
      preferredPort: null,
      webEmbedder: "webview",
    },
    {
      id: "difit",
      name: "Difit",
      enabled: true,
      surface: "web",
      commandTemplate: "difit . --host 127.0.0.1 --port {{ port }} --no-open --keep-alive",
      cwdTemplate: "{{ session.worktree_path }}",
      requiresSession: true,
      urlTemplate: "http://127.0.0.1:{{ port }}",
      preferredPort: 4966,
      webEmbedder: "iframe",
    },
    {
      id: "github",
      name: "GitHub",
      enabled: true,
      surface: "web",
      commandTemplate: "",
      cwdTemplate: "",
      requiresSession: false,
      urlTemplate: "https://github.com",
      preferredPort: null,
      webEmbedder: "webview",
    },
  ],
  kanban: {
    defaultAgentProfile: "claude",
    planningPromptAppend: "",
    implementationPromptAppend: "",
    reviewPromptAppend: "",
    startupSidebar: "restore",
  },
  experiments: EXPERIMENT_DEFAULTS,
};

// Re-export frontend-only task types
export type { TaskRun } from "./types/tasks";

// Re-export event types (not yet generated by specta)
export type { WatchUpdateEvent } from "./types/watches";
