// TaskDefinition, TaskGroup, and KeepOpen are now generated by specta
// in $lib/bindings.ts and re-exported via $lib/types.ts.
// This file only contains frontend-only types.

export interface TaskRun {
  taskId: string;
  ptyId: string;
  paneId: string | null;
  status: "running" | "succeeded" | "failed";
  exitCode: number | null;
  outputLines: string[];
  startedAt: number;
}
