// Most watch types are now generated by specta in $lib/bindings.ts
// and re-exported via $lib/types.ts.
// This file only contains frontend-only event types.

import type { Watch, WatchOutcome } from "$lib/bindings";

export interface WatchUpdateEvent {
  watch: Watch;
  changed: boolean;
  previousOutcome: WatchOutcome | null;
}
